### ISSUE TITLE
Can't get service worker when offline

### ISSUE THREAD

**Issue by BHouwens** [goldhand/sw-precache-webpack-plugin#51]
I'm generating the service worker using webpack 2. It's marked as registered and running in DevTools, works brilliantly on throttled connections, but fails to even get when fully offline. Just get a generic `An unknown error occurred when fetching the script.` failure.

I'm also working on `localhost` (not sure if that's relevant)

Not sure what other kind of information would be relevant here, but if I'm missing anything of importance let me know

**Comment by goldhand** [comment]
Paste your `SWPrecachWebpackConfig` here. It sounds like you need to add your index.html file to the plugin, if its not emitted by webpack, it wont be picked up by default.

If thats the case (I can't tell without seeing your config) you can just add it to the `staticFileGlobs` config and set `mergeStaticsConfig` to true:

something like:
```javascript
    new SWPrecacheWebpackPlugin(
      {
        staticFileGlobs: [
          'dist/index.html',
        ],
        mergeStaticsConfig: true,
      }
    ),
```
or just use a wildcard like `dist/**/*.html` to match any templates.

**Comment by BHouwens** [comment]
My html actually lives outside of the `dist` folder. So here's the config:

    new SWPrecache({
      cacheId: "byron-houwens",
      staticFileGlobs: [
        '**.html',
        'dist/**.js',
        'dist/**.css',
        'dist/**.svg',
        'dist/**.woff',
        'dist/**.woff2'
      ],
      handleFetch: true
    })

Not sure if having the html in the rest instead of `dist` makes a difference? I can see the html in the cache

**Comment by goldhand** [comment]
The `./index.html` shouldn't matter.

Are you testing in an incognito window? 

Do you have an `output.publicPath` in your webpack settings?
If so, is it different than the url your testing in.

**Comment by BHouwens** [comment]
No incognito window.

I've set the `publicPath` to `"/"` only. It's no more explicit than that right now

**Comment by NekR** [comment]
The `An unknown error occurred when fetching the script.` error means that ServiceWorker file itself, e.g. `service-worker.js`, cannot be downloaded. Not your assets.

The ServiceWorker is being downloaded by the browser each time you load a page in its scope. I don't know what you expected, but you are offline browser of course cannot download it from your server. Hence you have the error.

Than doesn't affect your already cached files by any means because you already run a ServiceWorker which handles them. That request which fails is to check if ServiceWorker file has been changed, i.e. check for an update.

Of course, if you don't have ServiceWorker registered in your page then you cannot download and register one when you are offline. Because you are offline.

**Comment by BHouwens** [comment]
I'm less concerned about the service worker's download and more about the assets. The `An unknown error occurred when fetching the script` is the only feedback returned though, so it's relevant to the case (as useless a piece of feedback as it may be).

The cached files weren't returned though, despite the already registered worker, which is the main issue (even if I am offline, since that's the point of the worker's registration and the caching of assets in the first place).

**Comment by NekR** [comment]
@BHouwens well, if you really want that to be solved you may bring contents of generated SW here. The only reasons why it may not work:

1) It failed to register at all, which seems to not be the case since it works for you with throttled network;
2) some required files aren't cached, e.g. `index.html` on `main.js` if you render from JS;
3) Routes are cached wrong, e.g. it's misinterpreted by `sw-precahe` because you didn't specify `stripPrefix: 'dist/'` (or something like that). Maybe the plugin handles this automatically
4) You cached you `index.html`, i.e. `/`, but try to reload the page from `/something` which isn't cached and you didn't specify `navigateFallback` for it

**Comment by BHouwens** [comment]
Hmm well that does give some direction thanks. It seems to be a fetch issue that has since cropped up and prevented the assets from downloading via service worker.. I'm not sure why this is necessarily, but I suspect it's route-related and will dig further.

Thanks for the help, feel free to close this (it seems to be specific to my project config)
