### ISSUE TITLE
I build production under Windows environment file error don't understand

### ISSUE THREAD

**Issue by zhangyanan151** [goldhand/sw-precache-webpack-plugin#56]
![image](https://cloud.githubusercontent.com/assets/16643246/23848072/635fb64e-0810-11e7-9d0d-bb9eadea09e8.png)
Uncaught (in promise) DOMException: Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script.
![image](https://cloud.githubusercontent.com/assets/16643246/23848123/a885ed6a-0810-11e7-9b03-b5cca386c043.png)
I am running in the HTTPS protocol

**Comment by joezimjs** [comment]
I believe it needs a valid SSL certificate unless it's running on localhost.

**Comment by zhangyanan151** [comment]
it's running on localhost but it doesn't work.

**Comment by zhangyanan151** [comment]
![image](https://cloud.githubusercontent.com/assets/16643246/24241163/dd8d4b08-0fee-11e7-86e8-ed383c5b7b13.png)

**Comment by joezimjs** [comment]
It may be running on localhost, but it looks like you're accessing it via 172.16.0.45, which the browser doesn't recognize as localhost. This shouldn't matter though because it is via https and you're using certs...

All I can say is that the errors are saying something is wrong with the SSL Certificates.

**Comment by goldhand** [comment]
closing due to this being an ssl cert issue
