### ISSUE TITLE
0.10.0 regression in create-react-app integration

### ISSUE THREAD

**Issue by jeffposnick** [goldhand/sw-precache-webpack-plugin#74]
## **BEFORE YOU SUBMIT** please read the following:
* [X] **I'm submitting a bug report**

**webpack version:**
2.x

**sw-precache-webpack-plugin version**:
0.10.0

**Please tell us about your environment:**
OSX 10.x

We've been working on a `create-react-app` integration, tracked inhttps://github.com/facebookincubator/create-react-app/pull/1728

https://github.com/facebookincubator/create-react-app/pull/1728#issuecomment-301998584 describes a regression when using `v0.10.0`+ of this plugin, in which the Webpack build process is run twice.

Looking at the change between `v0.9.1` and `v0.10.0`, I guess the issue might have been triggered by something around here: https://github.com/goldhand/sw-precache-webpack-plugin/compare/v0.9.1...v0.10.0?ws=0#diff-1fdf421c05c1140f6d71444ea2b27638R68

But I don't know enough about Webpack to say for sure.

**Comment by hulkish** [comment]
@jeffposnick can you try this with v0.11?

**Comment by jeffposnick** [comment]
Yes, the regression was introduced in `v0.10.0`, and I've been able to reproduce it in the subsequent versions, up to `v0.11.0`.

You should be able to reproduce by checking out this commit: https://github.com/jeffposnick/create-react-app/tree/f9b303aa038fedc79adc4ec6e6e94611ef2bae81

Then:

```sh
$ npm install && npm run build
```

**Comment by hulkish** [comment]
@jeffposnick hmm... I have seen this same issue myself progressively more and more lately. I am wondering if this issue is coming from within webpack itself? I'd have to dig to be sure.

In terms of timeline of the frequency I've seen this issue and how often webpack/sw-precache-webpack-plugin has done releases... It just points more toward webpack as the cause. 

I mean, it seems plain as day to me that `sw-precache-webpack-plugin` isn't the likely cause here. You can see [here](https://github.com/goldhand/sw-precache-webpack-plugin/blob/master/src/index.js#L71) that we are only doing a single operation once after-emit is applied.

**Comment by hulkish** [comment]
On another note.... I wonder if this could be solved by `sw-precache-webpack-plugin` could solve this by listening for `emit` instead of `after-emit`. Thoughts @goldhand ?

**Comment by goldhand** [comment]
The only thing I can think of is that I started using webpack's built in `writeFile` instead of nodejs `fs` [here](https://github.com/goldhand/sw-precache-webpack-plugin/compare/v0.9.1...v0.10.0?ws=0#diff-1fdf421c05c1140f6d71444ea2b27638R164
) (because of #64).

Tomorrow morning I'll try switching to using `fs` again and also test @hulkish theory about `emit`/`after-emit`. I'll keep digging into this issue until I find a fix because it looks like its blocking the facebookincubator/create-react-app#1728 pr.

Thanks for being so involved @hulkish, if you find anything or have any other ideas keep us posted :smile:

**Comment by jeffposnick** [comment]
Re: `create-react-app`, the PR landed using `v0.9.1`. So it's not blocking anything, and thanks again for everyone's hard work in maintaining this plugin. It should be getting a significant uptick in usage soon 😄

**Comment by goldhand** [comment]
I'm having trouble reproducing the two webpack builds error discovered by @Timer https://github.com/facebookincubator/create-react-app/pull/1728#issuecomment-301998584

I tried with / without dynamic chunks but still can't reproduce it with 0.11.0

**Comment by goldhand** [comment]
I think we want this latest version to be in **cra** btw, it supports webpack chunks.

**Comment by goldhand** [comment]
I think @hulkish is correct, this doesn't seem like a sw-precache-webpack-plugin issue. I have not been able to reproduce it yet.

**Comment by hulkish** [comment]
@goldhand actually, I've been able to reproduce it... be sure to check out the particular commit he mentioned: 

```bash
git clone https://github.com/jeffposnick/create-react-app.git
cd create-react-app
git checkout f9b303aa038fedc79adc4ec6e6e94611ef2bae81
```

**Comment by goldhand** [comment]
Ty @hulkish, I was using the facebook/create-react-app master branch. I don't see that problem there btw. Will test with jeffposnick's repo though

**Comment by hulkish** [comment]
@goldhand I'm actually working on a pretty big pr for you.. I think that if we are the cause of this issue... then my approach should fix that. 

My pr will bring:

- complete support of the webpack compiler instance's `inputFileSystem` & `outputFileSystem` :
  - **all the way down to the `swPrecache.generate()` level**.
  - It does this by processing the `swPrecache.generate()` in a node vm. This allows me to override and mock the require of the `fs` module.

- I've changed the processing strategy for this plugin to one very similar to how `html-webpack-plugin` solves this.

  1. ln SWPrecachePlugin.prototype.apply I listen for the `compiler.plugin('make')` event. 
    - This is after webpack has already walked through your code and acquired all resource paths. 
    - But before the compilation has begun.
    - This allows us to run in **parallel** with the parent compilation.
  2. In the handler for this event i create a child compiler.
  3.  in **parallel** to the main compilation by tapping into the parent/main compilation's `make` lifecycle event.

- Deprecated `minify` option.
  - Since output assets are properly recorded to the active webpack compilation, the output will be minified by any included minification plugin to your webpack config. 
  - For example: `new webpack.optimize.UglifyJsPlugin()`

**Comment by goldhand** [comment]
That is awesome @hulkish, Winning!

**Comment by goldhand** [comment]
How's it coming @hulkish? I'm really excited to see the node vm part of your solution 😄

**Comment by jeffposnick** [comment]
Thanks to @goldhand and especially @hulkish for diving into this!

I think it's probably too late in the `sw-precache` development lifecycle to fundamentally change the way it handles manifest generation, so apologies that the monkey-patches are necessary.

That being said, the current [`workbox-webpack-plugin`](https://github.com/GoogleChrome/workbox/tree/master/packages/workbox-webpack-plugin) (roughly equivalent to what `sw-precache-webpack-plugin` is trying to achieve, but for the new [Workbox](https://workboxjs.org/) set of libraries) is a *very* lightweight wrapper right now. If you think the approach that you're taking for `sw-precache-webpack-plugin` is generally useful, then perhaps there's some willingness to port it forward to `workbox-webpack-plugin`?

CC: @prateekbh, who's been developing `workbox-webpack-plugin` on our team. See also https://github.com/GoogleChrome/workbox/issues/269, which includes an early design discussion.

**Comment by hulkish** [comment]
@goldhand @jeffposnick so, the vm solution will work but i kind of hate it, lol.

It's really just a way to work around what se-precache doesnt expose independently (fs to support memoryfilesystem.

The real challenge I'm finding is the reliability of this approach. It's a fairly fragile approachbased on implementation detail of sw-precache. Which could have really annoying impact on supporting future versions of sw-precache.

For example... its not quite so simple as to run it in a VM because there is various other internals of sw-precache that generally make it a very awkward fit to the webpack plugin system. 

So.. here's what i want to do instead:

1. Rewrite sw-precache with a webpack-first approach. .
  - This involves basically just isolating and exposing the options defaulting/processing & lodash template compiling. (I've actually already done most of this... but wanted to get but in from you peeps before going too far)
2. First class support for webpack-dev-server, HMR & strictly using `inputFileSystem`/`outputFileSystem` for all source/asset input/output.
3. Borrowing quite a bit from html-webpack-plugin's approach


### Why?
- When it comes down to it... we really only need one thing from sw-precache: the lodash template.
- A part from processing options etc... Every single thing else that sw-precache is doing within it's `generate` method is undesired from a webpack
- I am convinced it's worth the effort because right now the way the service worker is generated is very black boxed. 
- Still early to boast i guess..but unless a giant anvil falls in the code somehow this approach is going to be way faster.


Other notes...

- While this obviously would be a breaking change.. I intend to keep the whole purpose of sw-precache to remain the same.
- This will really open this plugin up a bit more to allow it to integrate.more smoothly all around.
- I'm happy to first submit my sw-precache rewrite as a pr there...but i have doubts they'll fully convert to my approach. 
- I believe it's probably best to cut the direct `sw-precache` dependency and move forward with the essentials. (template..sw-toolbox etc)

**Comment by goldhand** [comment]
Thanks for the update @hulkish, I will continue to think on this. I've been down the rabbit hole a couple times and haven't been able to find a working solution for webpack-dev-server + sw-precache so I was really interested to see how the vm solution would work.

Maybe create branch that uses https://github.com/GoogleChrome/workbox instead of sw-precache (as opposed to rewriting sw-precache). As @jeffposnick mentioned, it will be a lot easier to get your ideas into workbox than sw-precache.

I don't think we can re-write sw-precache, and I'm not sure we should remove it from this plugin (considering it's called sw-precache-webpack-plugin) but if we can get webpack-dev-server working with all the sw-precache benefits, I suppose we could try it :smile:


I would like to get a fix for create-react-app though and release it in **0.11.1** so create-react-app can have chunk support. Any luck figuring out the issue with the duplicate build?

**Comment by hulkish** [comment]
@goldhand ur probably right. I actually am not very familiar with workbox at all. But, it does look a bit more plausible per my concerns.

However, it still doesn't support a dependency injected file system. They are still using fs directly. 

For now, im thinking ill go back to my solution of using  vm just to at least make it work with webpack-dev-server. Ill let you know if that changes.

**Comment by prateekbh** [comment]
@hulkish if you are interested i'll be happy to give u hand with workbox, or if u wanna comeback and do it after you are done with sw-precache

**Comment by jeffposnick** [comment]
Workbox's precaching logic assumes that it will be passed an array containing a "manifest" of URLs. The manifest entries can either be an Object, in which case both the `url` and `revision` fields should be present, or a String, which is assumed to be a URL that already includes revisioning information via a hash in the filename. E.g.:

```js
[
  {url: '/path/to/index.html', revision: '<hash_of_index.html>'},
  '/path/to/versioned/file.<hash>.js',
  // ...etc.
]
```

It's up to the build tool to generate an appropriate manifest corresponding to the current assets and "inject" it into a well-known placeholder in a source service worker file:

```js
const workboxSW = new WorkboxSW();

// The source file contains an empty array as a placeholder:
workboxSW.precache([]);

// After the build process has completed, the final file has [] replaced with the manifest:
// workboxSW.precache([/*actual manifest*/]);
```

The process of generating the manifest is up to the build tool.

We shipped Workbox v1.0.0 with some tools that follow the `sw-precache` model and use glob patterns to read from the filesystem, but if it makes sense to do something different for a Webpack plugin, then that's a legitimate use case.

Ideally, the options that the Webpack plugin supported would be roughly equivalent to what other Workbox build tools supported, but if it made sense not to support, e.g., [`globPatterns`](https://workboxjs.org/reference-docs/latest/module-workbox-build.html#.injectManifest) and instead just infer the assets based on the output of the Webpack build, (along with a provision to white/blacklist certain assets), that sounds reasonable to me.

**Comment by goldhand** [comment]
@jeffposnick, if I understand correctly, we can generate a **manifest** (array of filepaths) and provide that to `workboxSW.prechache(manifest)`.

Is `glob` not used then, if we provide the manifest?


As @hulkish mentioned, there is some mismatch with sw-precache and webpack coming from sw-precache's reliance on glob.

Webpack knows the all the filepaths (and revisions) so that feature in sw-precache is a hinderance (for usage with webpack).

If we can generate the manifest (and avoid the usage of glob) that would really be awesome!

**Comment by jeffposnick** [comment]
Basically, yes.

If you have a URL that already is versioned (because it has a hash in its URL thanks to Webpack), then you can just pass that string in as an entry in the array. URLs that can't be versioned (like most HTML documents) need to be specified in the `{url: '/path/to/index.html', revision: '<hash_of_index.html>'}` format, rather than as a string.

`workbox-build` is just one approach to generating this manifest. As long as the manifest adheres to that format I've described, it can be created via some other process (like by listening to the output of a Webpack build).

The actual process of spitting out a final `service-worker.js` file that has proper references to the `workbox-sw` runtime library and has the manifest in the right place (i.e. `workboxSW.precache(<manifest>)`) is the other piece of the puzzle, but that's largely a matter of [templating](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/templates/sw.js.tmpl).

**Comment by madou** [comment]
since a bit of discussion is happening with this vs workbox. anyone have a suggestion for the most appropriate plugin to use today?
